### ISSUE TITLE
Option for simple string transformations

### ISSUE THREAD

**Issue by klieret** [beet/page-headings-obsidian-plugin#2]
Thank you for this plugin, it's awesome!

One thing that would improve it even more for my use case is string transformations. For example to replace underscores `_` with spaces and apply an automatic capitalization.

My file names are usually of the form `this_is_a_note.md`, but the headers should be something like `This is a note`.

**Comment by klieret** [comment]
I've implemented this concrete use case in [my fork](https://github.com/klieret/page-headings-obsidian-plugin).

@beet : We could just pull these changes here, if you want. I think almost everyone would want to replace underscores/capitalize the first word, so I don't think this will break much. What do you think?

**Comment by beet** [comment]
Awesome, thanks @klieret, looks great!

What do we need to do to bring your fork in and get it to propagate out to the Obsidian plugins?

**Comment by klieret** [comment]
I just opened a PR :) 

To update the plugin, you will probably need to create a new release as explained [here](https://publish.obsidian.md/hub/04+-+Guides%2C+Workflows%2C+%26+Courses/Guides/How+to+release+a+new+version+of+your+plugin)?

**Comment by beet** [comment]
Thanks again for contributing this, I've created a new release and it's available through Obsidian already.
